"""Updated id to be UUID. Added name column to user table.

Revision ID: 8e97ba30bab4
Revises: 003190f70aa4
Create Date: 2024-06-21 14:26:08.209833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision = '8e97ba30bab4'
down_revision = '003190f70aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add the new UUID column
        batch_op.add_column(sa.Column('new_id', sa.UUID(as_uuid=True), nullable=False, server_default=sa.text("uuid_generate_v4()"), primary_key=True))
        
        # Drop the original id column
        batch_op.drop_column('id')
        
        # Rename the new_id column to id
        batch_op.alter_column('new_id', new_column_name='id', existing_type=sa.UUID(), existing_nullable=False)
        
        # Add the new name column
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.alter_column('id',
               existing_type=UUID(as_uuid=True),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
